param_grid: 
    max_depth: [2, 3, 4, 5]
    n_estimators: [25, 50, 100, 200, 300, 400]
    colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
    subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
    min_child_weight: [3, 4, 5, 6, 8, 10]
    enable_categorical: [False]
cv: 5
n_jobs: -1
verbose: True

                                                                               